version: '3.1'
services:
  control-products:
    build: control-products
    image: control-products
    container_name: control_products_container
    ports:
      - "9090:9090"
    depends_on:
      - warehouse-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://warehouse-db:5432/warehouse
      - SPRING_DATASOURCE_USERNAME=warehouse
      - SPRING_DATASOURCE_PASSWORD=warehouse

  warehouse-db:
    image: postgres:14-alpine
    container_name: warehouse_db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=warehouse
      - POSTGRES_USER=warehouse
      - POSTGRES_DB=warehouse

  shopping-list:
    build: shopping-list
    image: shopping-list
    container_name: shopping_list_container
    ports:
      - "8080:8080"
#    depends_on:
#      - stats-server
#      - ewm-db
#    environment:
#      - STATS_SERVER_URL=http://stats-server:9090
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
#      - SPRING_DATASOURCE_USERNAME=ewm
#      - SPRING_DATASOURCE_PASSWORD=ewm
#
#  ewm-db:
#    image: postgres:14-alpine
#    container_name: ewm_db_container
#    volumes:
#      - /var/lib/postgresql/data/
#    ports:
#      - "6542:5432"
#    environment:
#      - POSTGRES_PASSWORD=ewm
#      - POSTGRES_USER=ewm
#      - POSTGRES_DB=ewm-db
