create table if not exists categories
(
    id   bigint generated by default as identity primary key,
    name varchar(120) not null
);

create table if not exists goods
(
    id          bigint generated by default as identity primary key,
    name        varchar(120) not null,
    category_id bigint       not null references categories (id),
    price       float4
);

create table if not exists places
(
    id   bigint generated by default as identity primary key,
    name varchar(120) not null
);

create table if not exists local_goods
(
    id            bigint generated by default as identity primary key,
    good_id       bigint    not null references goods (id),
    place_id      bigint    not null references places (id),
    purchase_date timestamp not null,
    beep          boolean
);

create table if not exists expiration_date
(
    id                  bigint generated by default as identity primary key,
    category_id         bigint not null references categories (id),
    place_id            bigint not null references places (id),
    number_days_storage int4   not null
);

insert into categories (name)
values ('Мясо и мясная продукция'),
       ('Рыба и рыбная продукция'),
       ('Овощи'),
       ('Фрукты'),
       ('Зелень'),
       ('Молочная продукция'),
       ('Яйца'),
       ('Масла'),
       ('Сахар'),
       ('Кондитерская продукция'),
       ('Зерномучная');

insert into places (name)
values ('Холодильник'),
       ('Морозилка'),
       ('Шкаф');

insert into goods (name, category_id, price)
values ('Котлеты микоян', '1', '120.50'),
       ('Форель карельская', '2', '600.00'),
       ('Картофель фермерский', '3', '30.50'),
       ('Бананы Аргентина', '4', '98.00'),
       ('Укроп Три листа', '5', '33.50'),
       ('Молоко ВМ', '6', '86.00'),
       ('Яйца Акрополь', '7', '135.00'),
       ('Кубаночка, подсолнечное масло', '8', '120.00'),
       ('Рафинад КМ', '9', '130.00'),
       ('торт Санчо', '10', '800.50'),
       ('Макфа макароны', '11', '89.00');